### PR TITLE
Fixed runc version

### PR DESCRIPTION
**Pull request by zozo123**
pass the version and gitcommit to runc on compilation time and updated the commit ID and repository to work with resin-os/runc

### CODE REVIEW

**Comment by petrosagg** [comment]
Is there a way of extracting the same data using the commit from vendor.conf? It's duplicated 3 times right now and something tells me that when we update the runc we bring in we'll forget to change all occurences

**Comment by zozo123** [comment]
@petrosagg, it should be fine now. We can add some mechanism to get the VERSION from github and the commit when parsing the vevndor.conf. If you want I'll do that, but the current commit follows the logic of the original code. `# When updating RUNC_COMMIT, also update runc in vendor.conf accordingly`

**Comment by zozo123** [comment]
On a second thought, let me try to have a script (external to .binary) that
retrieves all of this from the vendor.conf and pull VERSION according to
the commit in the vendor.conf file.

**Comment by petrosagg** [comment]
@zozo123 any progress with this?

**Comment by zozo123** [comment]
@petrosagg, I thought about it again, please see the last commit, there are 2 places where one needs to update the version, same as it's in offical docker. The point of this test is to verify it instead of having smart parsing as part of the build. I think that we should take it now as-is and maybe later to implement all the parsing on the main branch and even submit to moby itself. Let me know what you think

**Pull request merged**
